# # GOOGLE CHROME REPOS
# - name: ADD APT KEY CHROME
#   apt_key:
#     url: https://dl.google.com/linux/linux_signing_key.pub
#     state: present
#   tags:
#   - google

# - name: ADD REPOS CHROME
#   apt_repository:
#     repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
#     state: present
#     filename: google
#   tags:
#   - google

# # SPOTIFY REPOS
# - name: ADD APT KEY SPOTIFY
#   apt_key:
#     url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
#     state: present
#     keyring: /etc/apt/trusted.gpg.d/spotify.gpg
#   tags:
#   - spotify

# - name: ADD REPOS SPOTIFY
#   apt_repository:
#     repo: deb http://repository.spotify.com stable non-free
#     state: present
#     filename: spotify
#   tags:
#   - spotify