
# # SPOTIFY REPOS
# - name: ADD APT KEY SPOTIFY
#   apt_key:
#     url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
#     state: present
#     keyring: /etc/apt/trusted.gpg.d/spotify.gpg
#   tags:
#   - spotify

# - name: ADD REPOS SPOTIFY
#   apt_repository:
#     repo: deb http://repository.spotify.com stable non-free
#     state: present
#     filename: spotify
#   tags:
#   - spotify