# GOOGLE CHROME REPOS
- name: ADD APT KEY CHROME
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  tags:
  - google

- name: ADD REPOS CHROME
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google
  tags:
  - google

# CONFIGURE VSCODE REPOS
- name: INSTALL KEY VSCODE
  become: true
  ansible.builtin.get_url:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    keyring: /etc/apt/keyrings/packages.microsoft.gpg
  tags:
  - vscode

- name: ADD REPOS 1PASS
  apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    state: present
    filename: vscode
  tags:
  - vscode
  
# CONFIGURE HASHICORP REPOS
- name: ADD APT KEY HASHCORP
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: ADD REPOS HASHCORP
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main
    state: present
    filename: hashicorp

# CONFIGURE 1PASSWORD REPOS
- name: ADD APT KEY 1PASS
  tags:
  - 1pass
  ansible.builtin.apt_key:
    id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
    url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: /usr/share/keyrings/1password-archive-keyring.gpg

- name: ADD REPOS 1PASS
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main
    state: present
    filename: 1password
  tags:
  - 1pass

# LENS REPOS
- name: ADD APT KEY LENS
  apt_key:
    url: https://downloads.k8slens.dev/keys/gpg
    state: present
    keyring: /usr/share/keyrings/lens-archive-keyring.gpg
  tags:
  - lens

- name: ADD REPOS LENS
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/lens-archive-keyring.gpg] https://downloads.k8slens.dev/apt/debian stable main
    state: present
    filename: lens
  tags:
  - lens

# INSOMNIA REPOS
- name: ADD REPOS INSOMNIA
  apt_repository:
    repo: deb [trusted=yes arch=amd64] https://download.konghq.com/insomnia-ubuntu/ default all
    state: present
    filename: insomnia
  tags:
  - insomnia

# SPOTIFY REPOS
- name: ADD APT KEY SPOTIFY
  apt_key:
    url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/spotify.gpg
  tags:
  - spotify

- name: ADD REPOS SPOTIFY
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    filename: spotify
  tags:
  - spotify