---
- name: ADD THE FLATHUB FLATPAK REPOSITORY REMOTETO THE USER INSTALLATION
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

# - name: INSTALL FLATPAK APPS
#   community.general.flatpak:
#     name:
#     method: system