---
- name: ADD THE FLATHUB FLATPAK REPOSITORY REMOTETO THE USER INSTALLATION
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: INSTALL FLATPAK APPS
  community.general.flatpak:
    name:
      - com.spotify.Client
      - com.getpostman.Postman
      - com.jetbrains.IntelliJ-IDEA-Ultimate
      - com.jetbrains.GoLand
      - com.jetbrains.PyCharm-Professional
      - com.jetbrains.DataGrip
      - com.jgraph.drawio.desktop
    method: system