- name: ADD APT KEY CHROME
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  tags:
  - google

- name: ADD REPOS CHROME
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google.list
  tags:
  - google

- name: INSTALAR PACKS CHROME
  apt:
    name: '{{ packages }}'
    state: present
  become: true
  vars:
    packages:
      - google-chrome-stable
  tags:
  - google