- name: UPDATE PACKS
  tags: default
  apt:
    upgrade: dist
    force_apt_get: yes

- name: "INSTALL DEFAULT PACKS"
  tags: 
  - default
  - apps
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - vim
      - curl
      - wget
      - remmina
      - zenity
      - flameshot
      - alacarte
      - htop
      - btop
      - nmap
      - wireguard
      - resolvconf
      - flatpak
      - snapd
      - resolvconf
      - wireguard
      - google-chrome-stable
      - ca-certificates
      - apt-transport-https
      - code
      - terraform
      - vagrant
      - 1password
      - lens
      - insomnia

- name: RECONFIGURE RESOLVCONF
  command: sudo dpkg-reconfigure -f noninteractive resolvconf

- name: COPY SCRIPT FOR INSTALL JETBRAINS TOOLBOX
  ansible.builtin.copy:
    src: ./files/jetbrains-toolbox.sh
    dest: /home/{{ usuario }}/Downloads/jetbrains-toolbox.sh
    mode: '0777'
  tags: 
  - default
  - apps

- name: EXECUTE SCRIPT FOR INSTALL JETBRAINS TOOLBOX
  ansible.builtin.shell: /home/{{ usuario }}/Downloads/jetbrains-toolbox.sh >> /tmp/jetbrains.txt
  tags: 
  - default
  - apps
