---
- name: UPDATE PACKS
  tags: default
  apt:
    upgrade: dist
    force_apt_get: yes

- name: "INSTALL DEFAULT PACKS"
  tags: default
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - vim
      - curl
      - wget
      - remmina
      - zenity
      - flameshot
      - alacarte
      - htop
      - btop
      - nmap
      - wireguard
      - resolvconf
      - flatpak
      - snapd

- name: REMOVE UNECESSARY APPS
  tags:
    - default
    - clean
  include_tasks: cleanApp.yml

- name: INSTALL WIREGUARD PACKS
  tags:
    - wireguard
    - default
  include_tasks: wireguard.yml

- name: INSTALL HASHCORP PACKS
  tags:
    - hashcorp
    - default
  include_tasks: hashicorp.yml

- name: INSTALL VSCODE PACKS
  tags:
    - vscode
    - default
  include_tasks: vscode.yml

- name: INSTALL GOOGLE PACKS
  tags:
    - google
    - default
  include_tasks: google.yml

- name: INSTALL 1PASSWORD PACKS
  tags:
    - 1pass
    - default
  include_tasks: 1pass.yml

- name: INSTALL SNAPS PACKS
  tags:
    - snaps
    - default
  include_tasks: snap.yml

- name: INSTALL FLATPAK PACKS
  tags:
    - flatpak
    - default
  include_tasks: flatpak.yml