- name: REMOVE VSCODE FLATPAK APP
  tags:
  - vscode
  community.general.flatpak:
    name:
      - com.visualstudio.code
    method: system
    state: absent


- name: INSTALL DEPENDENCIES
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - apt-transport-https
    state: present
  tags:
  - vscode

- name: CREATE APT KEYRINGS DIR
  become: true
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: directory
    mode: 'u=rwx,go=rx'
  tags:
  - vscode

- name: INSTALL KEY
  become: true
  ansible.builtin.get_url:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    dest: '/etc/apt/keyrings/'
    mode: 'u=rw,go=r'
    force: true
  tags:
  - vscode
  
- name: INSTALL VSCODE
  become: true
  ansible.builtin.apt:
    name:
      - code
    state: present
  tags:
  - vscode